spring.application.name=logMonitor
server.port=5000

logging.level.root=INFO
logging.level.dev.logMonitor=INFO

spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.ai.ollama.base-url=http://localhost:11434